rvm: 2.0.0
language: objective-c
osx_image: xcode8
install:
  - ./install_swiftlint.sh
script:
  - bundle install
  - gem install travis --no-rdoc --no-ri
  - travis lint .travis.yml --no-interactive
  - bundle exec danger
  - swiftlint
  - xcodebuild clean build -workspace NSManchester.xcworkspace -scheme NSManchester -destination "platform=iOS Simulator,name=iPhone 6S" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
